/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg11711357_claudiacortes;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Claudia Cortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pb_lluvias2017 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pb_Laureles = new javax.swing.JProgressBar();
        pb_Concepcion = new javax.swing.JProgressBar();
        pb_FranciscoMorazan = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Represas = new javax.swing.JTree();
        btn_refrescar = new javax.swing.JButton();
        lbl_dia = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pb_consumoPoblacion = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        pb_Generacion_Energia = new javax.swing.JProgressBar();
        btn_inicio = new javax.swing.JButton();
        btn_detener = new javax.swing.JButton();
        btn_Continuar = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador Consumo de Agua");

        jLabel1.setText("Lluvias 2017");

        pb_lluvias2017.setMaximum(199650);
        pb_lluvias2017.setOrientation(1);

        jLabel2.setText("Max");

        jLabel3.setText("Dia");

        pb_Laureles.setMaximum(29498);
        pb_Laureles.setOrientation(1);

        pb_Concepcion.setMaximum(49913);
        pb_Concepcion.setOrientation(1);

        pb_FranciscoMorazan.setMaximum(117793);
        pb_FranciscoMorazan.setOrientation(1);

        jLabel4.setText("Los Laureles ");

        jLabel5.setText("Concepcion");

        jLabel6.setText("Francisco Morazan");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Represas");
        jt_Represas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_Represas);

        btn_refrescar.setText("Refrescar");
        btn_refrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refrescarMouseClicked(evt);
            }
        });

        lbl_dia.setText("DIAS");

        jLabel8.setText("Consumo de la población. ");

        pb_consumoPoblacion.setMaximum(9275);

        jLabel9.setText("Generacion de Enegercia Electrica");

        pb_Generacion_Energia.setMaximum(9275);

        btn_inicio.setText("Inicio");
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        btn_detener.setText("Detener");
        btn_detener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_detenerMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_detenerMouseClicked(evt);
            }
        });

        btn_Continuar.setText("Continuar");
        btn_Continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ContinuarMouseClicked(evt);
            }
        });

        btn_Guardar.setText("Guardar Registros");
        btn_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pb_lluvias2017, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_dia)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pb_Laureles, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pb_Concepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(pb_FranciscoMorazan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_refrescar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pb_consumoPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pb_Generacion_Energia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_inicio)
                        .addGap(43, 43, 43)
                        .addComponent(btn_detener, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pb_lluvias2017, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lbl_dia)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btn_refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pb_FranciscoMorazan, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pb_Concepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pb_Laureles, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(pb_consumoPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pb_Generacion_Energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_detener, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Continuar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        adm_Archivo Datos = new adm_Archivo("./Examen2.txt");
        Datos.CargarArchivo();
        /*OBETENEMOS LOS VALORES DEL ARCHIVO*/
        IndicadorDia = Datos.getIndicadorDia();
        Indicador_crecimiento = Datos.getIndicador_crecimiento();
        Prom_Lluvia_Diaria = Datos.getProm_Lluvia_Diaria();
        Indicador_Porcentaje_Represas = Datos.getIndicador_Porcentaje_Represas();
        Re_1 = Datos.getRe_1();//Los Laureles.
        Re_2 = Datos.getRe_2();//La concepcion.
        Re_3 = Datos.getRe_3();//Fco. Morazan.
        /*INDICADORES DE CONSUMO*/
        In_1 = Datos.getIn_1();//Los Laureles.
        In_2 = Datos.getIn_2();//La concepcion.
        In_3 = Datos.getIn_3();//Fco. Morazan.
        lbl_dia.setText(IndicadorDia + "");
        /*CARGAMOS LOS VALORES AL ARBOL*/
        DefaultTreeModel modelo = (DefaultTreeModel) jt_Represas.getModel();
        DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(Re_1.get(0));
        DefaultMutableTreeNode sub_nodo = new DefaultMutableTreeNode(Re_1.get(1));
        nodo.add(sub_nodo);
        DefaultMutableTreeNode nodo1 = new DefaultMutableTreeNode(Re_2.get(0));
        DefaultMutableTreeNode sub_nodo1 = new DefaultMutableTreeNode(Re_2.get(1));
        nodo1.add(sub_nodo1);
        DefaultMutableTreeNode nodo2 = new DefaultMutableTreeNode(Re_3.get(0));
        DefaultMutableTreeNode sub_nodo2 = new DefaultMutableTreeNode(Re_3.get(1));
        nodo2.add(sub_nodo2);
        Raiz.add(nodo);
        Raiz.add(nodo1);
        Raiz.add(nodo2);
        modelo.reload();
        int Consumo1 = Integer.parseInt(In_1.get(1) + "");
        int Condumo2 = Integer.parseInt(In_2.get(1) + "");
        int Consumo3 = Integer.parseInt(In_3.get(1) + "");
        //boolean Vive, boolean avanza, JProgressBar barra, int Consumo1, int Condumo2, int Consumo3

        Hc = new hiloConsumo(true, true, pb_consumoPoblacion, Consumo1, Condumo2, Consumo3, pb_Laureles, pb_Concepcion, pb_FranciscoMorazan);
        He = new HiloEnergia(true, true, pb_Generacion_Energia, Consumo1, Condumo2, Consumo3);
        double porcentaje_1 = Double.parseDouble(Re_1.get(1) + "");
        double porcentaje_2 = Double.parseDouble(Re_2.get(1) + "");
        double porcentaje_3 = Double.parseDouble(Re_3.get(1) + "");
        //System.out.println("PORCENTAJE LOS LAURELES"+porcentaje_1);
        ConsumoAno = new hiloConsumoAno(true, true, pb_lluvias2017, lbl_dia, Prom_Lluvia_Diaria, Indicador_crecimiento);
        Laureles = new HiloRepresa(true, true, pb_Laureles, pb_lluvias2017, porcentaje_1);
        Concepcion = new HiloRepresa(true, true, pb_Concepcion, pb_lluvias2017, porcentaje_2);
        Fco_Morazan = new HiloRepresa(true, true, pb_FranciscoMorazan, pb_lluvias2017, porcentaje_3);
        ConsumoAno.start();
        Laureles.start();
        Concepcion.start();
        Fco_Morazan.start();
        Hc.start();
        He.start();

    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_detenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detenerMouseClicked
//        ConsumoAno.setAvanza(false);
//        Hc.setAvanza(false);
//        He.setAvanza(false);
//        Laureles.setAvanza(false);
//        Concepcion.setAvanza(false);
//        Fco_Morazan.setAvanza(false);
  JOptionPane.showMessageDialog(this,"Deteniendo...");
        ConsumoAno.stop();
        Hc.stop();
        He.stop();
        Laureles.stop();
        Concepcion.stop();
        Fco_Morazan.stop();
    }//GEN-LAST:event_btn_detenerMouseClicked

    private void btn_ContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ContinuarMouseClicked
//       ConsumoAno.setVive(!false);
//        Hc.setVive(!false);
//        He.setVive(!false);
//        Laureles.setVive(!false);
//        Concepcion.setVive(!false);
//        Fco_Morazan.setVive(!false);
        /*RECORDAR QUITAR*/
        JOptionPane.showMessageDialog(this,"Continuando...");
//        ConsumoAno.setAvanza(true);
//        Hc.setAvanza(true);
//        He.setAvanza(true);
//        Laureles.setAvanza(true);
//        Concepcion.setAvanza(true);
//        Fco_Morazan.setAvanza(true);
        // ConsumoAno.start();
        /*------------*/
       try{
             ConsumoAno.start();
        Hc.start();
        He.start();
        Laureles.start();
        Concepcion.start();
        Fco_Morazan.start();
         ConsumoAno.setAvanza(true);
        Hc.setAvanza(true);
        He.setAvanza(true);
        Laureles.setAvanza(true);
        Concepcion.setAvanza(true);
        Fco_Morazan.setAvanza(true);
       }catch(Exception e){
           
       }
    }//GEN-LAST:event_btn_ContinuarMouseClicked

    private void btn_refrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescarMouseClicked
        int Valor1;
        int Valor2;
        int Valor3;
        double porcentaje_1 = Double.parseDouble(Re_1.get(1) + "") * pb_Laureles.getValue();
        double porcentaje_2 = Double.parseDouble(Re_2.get(1) + "") * pb_Concepcion.getValue();
        double porcentaje_3 = Double.parseDouble(Re_3.get(1) + "") * pb_FranciscoMorazan.getValue();
        DefaultTreeModel modelo = (DefaultTreeModel) jt_Represas.getModel();
        DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) Raiz.getChildAt(0);
        DefaultMutableTreeNode nodo1 = (DefaultMutableTreeNode) Raiz.getChildAt(1);
        DefaultMutableTreeNode nodo2 = (DefaultMutableTreeNode) Raiz.getChildAt(2);
        nodo.removeAllChildren();
        nodo1.removeAllChildren();
        nodo2.removeAllChildren();
        nodo.add(new DefaultMutableTreeNode(porcentaje_1));
        nodo1.add(new DefaultMutableTreeNode(porcentaje_2));
        nodo2.add(new DefaultMutableTreeNode(porcentaje_3));
        modelo.reload();
        JOptionPane.showMessageDialog(this, "Se han actualizado los porcentajes");
    }//GEN-LAST:event_btn_refrescarMouseClicked

    private void btn_detenerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detenerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_detenerMouseEntered

    private void btn_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarMouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.showSaveDialog(this);
        String Ruta = jfc.getSelectedFile().getPath() + ".txt";
        adm_Archivo AA = new adm_Archivo(Ruta);
        AA.setIndicadorDia(Integer.parseInt(lbl_dia.getText()));
        Re_1.remove(1);
        Re_2.remove(1);
        Re_3.remove(1);
        //ELIMINAMOS LOS VIEJOS NIVELES
        Re_1.add(pb_Laureles.getValue());
        Re_2.add(pb_Laureles.getValue());
        Re_3.add(pb_Laureles.getValue());
        AA.setRe_1(Re_1);
        AA.setRe_2(Re_2);
        AA.setRe_3(Re_3);
        try {
            AA.EscribirArchivo(pb_consumoPoblacion.getValue(), pb_Generacion_Energia.getValue(), pb_FranciscoMorazan.getValue());
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_GuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Continuar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_detener;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_refrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jt_Represas;
    private javax.swing.JLabel lbl_dia;
    private javax.swing.JProgressBar pb_Concepcion;
    private javax.swing.JProgressBar pb_FranciscoMorazan;
    private javax.swing.JProgressBar pb_Generacion_Energia;
    private javax.swing.JProgressBar pb_Laureles;
    private javax.swing.JProgressBar pb_consumoPoblacion;
    private javax.swing.JProgressBar pb_lluvias2017;
    // End of variables declaration//GEN-END:variables
 int IndicadorDia = 0;
    int Indicador_crecimiento = 0;
    int Prom_Lluvia_Diaria = 0;
    double Indicador_Porcentaje_Represas = 0.0;
    ArrayList Re_1 = new ArrayList();//Los Laureles.
    ArrayList Re_2 = new ArrayList();//La concepcion.
    ArrayList Re_3 = new ArrayList();//Fco. Morazan.
    /*INDICADORES DE CONSUMO*/
    ArrayList In_1 = new ArrayList();//Los Laureles.
    ArrayList In_2 = new ArrayList();//La concepcion.
    ArrayList In_3 = new ArrayList();//Fco. Morazan.
    hiloConsumo Hc;
    HiloEnergia He;
    HiloRepresa Laureles;
    HiloRepresa Concepcion;
    HiloRepresa Fco_Morazan;
    hiloConsumoAno ConsumoAno;
}
